spring:
  profiles:
    include: default
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.ewm@gmail.com
    password: DTuNgpzD1@@
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp
  thymeleaf:
    cache: false

logging:
  level:
    web: DEBUG

exchange-rates:
  access-key: c01d0cbc6bcd10252355222449d9ef85
  default-base-currency: ""

ewm:
  notification-service:
    technical-support: khoa.nguyen@hesmantech.com

period:
  delay-time: 10
  fail-attempt-threshold-amount:
    fixer-attempts: 3

email:
  noreply: noreply.ewm@gmail.com
