spring:
  profiles:
    active: prod
  devtools:
    add-properties: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/wcc_tableau
    username: postgres
    password: KhongCoPass1986@
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/db/master.xml

server:
  port: 8087

exchange-rates:
  base-url: http://data.fixer.io/api/
  default-symbols: "AED,CHF,EUR,GBP,USD,ZAR"
